// This file is auto-generated by ./bin/rails stimulus:manifest:update
// Run that command whenever you add a new controller or create them with
// ./bin/rails generate stimulus controllerName
import { Controller } from "@hotwired/stimulus"

export default class extends Controller {
  connect() {
    // Set the timeout for 5 seconds (5000ms)
    setTimeout(() => {
      this.dismiss()
    }, 1000)

  }
  dismiss() {
    // We use the Bootstrap 'fade' class logic or just hide it
    this.element.style.transition = "opacity 0.6s ease"
    this.element.style.opacity = "0"

    // Completely remove from DOM after the fade out
    setTimeout(() => {
      this.element.remove()
    }, 1000)
  }
}